version: "3.8"

services:
  monitor:
    build: ./monitor
    container_name: monitor
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./monitor/src:/usr/src/app/src
    command: ['npm', 'start']
#    command: ["sh", "-c", "sleep 2073600"]

#  node:
#    build: ./client
#    ports:
#      - 3001:3001
#    volumes:
#      - ./client/src:/usr/src/app/src
#    depends_on:
#      - monitor
#    command: [ 'npm', 'start' ]
##    command: ["sh", "-c", "sleep 2073600"]
